const fs=require("fs"), path=require("path");
const ROOT=__dirname, OUT=path.join(ROOT,"dist");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const slug=s=>String(s).toLowerCase().replace(/ä/g,"ae").replace(/ö/g,"oe").replace(/ü/g,"ue").replace(/ß/g,"ss").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const subcats={Kochen:["Hauptgerichte","Pasta & Pizza","Salate","Beilagen","Saucen & Dips","Snacks"],Backen:["Süß","Herzhaft"]};
function cp(src,dst){fs.mkdirSync(dst,{recursive:true});for(const e of fs.readdirSync(src,{withFileTypes:true})){const a=path.join(src,e.name),b=path.join(dst,e.name);e.isDirectory()?cp(a,b):fs.copyFileSync(a,b)}}
if(fs.existsSync(OUT))fs.rmSync(OUT,{recursive:true});fs.mkdirSync(OUT,{recursive:true});cp(path.join(ROOT,"static"),OUT);
const dir=path.join(ROOT,"content","recipes");
const recipes=fs.readdirSync(dir).filter(f=>f.endsWith(".json")).map(f=>({...JSON.parse(fs.readFileSync(path.join(dir,f),"utf8")),_file:f,_slug:f.replace(/\.json$/,"")})).sort((a,b)=>new Date(b.date)-new Date(a.date));
const sidebar=(active="")=>`<aside class="recipe-sidebar"><div class="sidebar-inner">${Object.entries(subcats).map(([cat,subs])=>`<section class="sidebar-group"><p>${cat.toUpperCase()}</p>${subs.map(s=>`<a class="${active===s?"active":""}" href="/kategorie-${slug(s)}.html">${esc(s)}</a>`).join("")}</section>`).join("")}</div></aside>`;
const head=(title,desc="")=>`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Courier+Prime:wght@400;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="/style.css"></head><body><header class="site-header"><div class="header-inner"><a class="brand" href="/">MaggisRezepte</a><label class="search-box"><span>⌕</span><input id="search" type="search" placeholder="Rezept suchen…"></label></div></header>`;
const card=r=>`<a class="recipe-card" href="/rezept-${r._slug}.html" data-search="${esc(`${r.title} ${r.category} ${r.subcategory}`.toLowerCase())}"><div class="thumb" style="background-image:url('${esc(r.image||"/images/rezept-demo.png")}')"></div><div class="recipe-info"><small>${esc(r.category.toUpperCase())} · ${esc(r.subcategory.toUpperCase())}</small><h3>${esc(r.title)}</h3><p>${esc(r.time)} · ${esc(r.servings)}</p></div><span class="arrow">→</span></a>`;
const catCards=()=>`<div class="home-category-grid">${Object.entries(subcats).map(([cat,subs])=>`<article class="home-category-card"><div class="tape"></div><p class="card-label">${cat.toUpperCase()}</p><h2>${cat}</h2><nav>${subs.map(s=>`<a href="/kategorie-${slug(s)}.html">${esc(s)} <span>›</span></a>`).join("")}</nav></article>`).join("")}</div>`;
const home=`${head("MaggisRezepte – Mein digitales Rezept-Notizbuch","Einfache Rezepte zum Kochen und Backen.")}<main class="home-layout">${sidebar()}<section class="home-paper"><div class="section-heading home-heading"><span>01</span><h1>Kategorien</h1></div>${catCards()}<div class="paper-divider"></div><div class="section-heading"><span>02</span><h2>Neue Rezepte</h2></div><div id="recipe-list" class="recipe-list home-recipe-list">${recipes.slice(0,8).map(card).join("")}</div></section></main><footer class="site-footer"><div><strong>MaggisRezepte</strong><span>Mein digitales Rezept-Notizbuch</span></div><nav><a href="#">Datenschutz</a><a href="#">Impressum</a></nav></footer><script src="/script.js"></script></body></html>`;
fs.writeFileSync(path.join(OUT,"index.html"),home);
for(const r of recipes){
 const jsonld={"@context":"https://schema.org","@type":"Recipe","name":r.title,"image":r.image?[r.image]:undefined,"recipeYield":r.servings,"recipeIngredient":r.ingredients,"recipeInstructions":r.steps.map(x=>({"@type":"HowToStep","text":x}))};
 const page=`${head(`${r.title} – MaggisRezepte`,`${r.title} – einfaches Rezept.`)}<main class="recipe-layout">${sidebar(r.subcategory)}<article class="recipe-paper"><nav class="breadcrumb"><a href="/">Startseite</a><span>›</span><a href="/kategorie-${slug(r.subcategory)}.html">${esc(r.category)}</a><span>›</span><a href="/kategorie-${slug(r.subcategory)}.html">${esc(r.subcategory)}</a></nav><h1>${esc(r.title)}</h1><div class="meta-row"><span>◷ ${esc(r.time)}</span><span>♙ ${esc(r.servings)}</span><span>▥ ${esc(r.difficulty)}</span></div>${r.image?`<figure class="recipe-image"><div class="photo-tape"></div><img src="${esc(r.image)}" alt="${esc(r.title)}"></figure>`:""}<section class="recipe-section"><h2><span>Zutaten</span></h2><ul>${(r.ingredients||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul></section><section class="recipe-section"><h2><span>Zubereitung</span></h2><ol>${(r.steps||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ol></section>${r.notes?`<section class="recipe-section"><h2><span>Notizen</span></h2><p>${esc(r.notes)}</p></section>`:""}<button class="print-button" onclick="window.print()">▣ &nbsp; Rezept drucken</button></article></main><script type="application/ld+json">${JSON.stringify(jsonld)}</script></body></html>`;
 fs.writeFileSync(path.join(OUT,`rezept-${r._slug}.html`),page);
}
for(const [cat,subs] of Object.entries(subcats))for(const sub of subs){
 const found=recipes.filter(r=>r.subcategory===sub);
 const p=`${head(`${sub} – MaggisRezepte`,`${sub} Rezepte`)}<main class="recipe-layout">${sidebar(sub)}<section class="home-paper category-page"><div class="section-heading home-heading"><span>${esc(cat.toUpperCase())}</span><h1>${esc(sub)}</h1></div><div id="recipe-list" class="recipe-list home-recipe-list">${found.length?found.map(card).join(""):`<p>Hier gibt es noch keine Rezepte.</p>`}</div></section></main><script src="/script.js"></script></body></html>`;
 fs.writeFileSync(path.join(OUT,`kategorie-${slug(sub)}.html`),p);
}
console.log(`MaggisRezepte gebaut: ${recipes.length} Rezepte`);
